name: proj2
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - decorator=5.1.1
  - expat=2.5.0
  - jupyter_client=8.6.0
  - libcxx=14.0.6
  - libffi=3.4.4
  - libsodium=1.0.18
  - matplotlib-inline=0.1.6
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.0.13
  - parso=0.8.3
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - python=3.12.2
  - python-dateutil=2.8.2
  - pyzmq=25.1.2
  - readline=8.2
  - six=1.16.0
  - sqlite=3.41.2
  - tk=8.6.12
  - xz=5.4.6
  - zeromq=4.3.5
  - zlib=1.2.13
  - pip:
      - anyio==4.3.0
      - appnope==0.1.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - attrs==23.2.0
      - babel==2.14.0
      - beautifulsoup4==4.12.3
      - behave==1.2.6
      - bleach==6.1.0
      - certifi==2024.2.2
      - cffi==1.16.0
      - chardet==5.2.0
      - charset-normalizer==3.3.2
      - colorama==0.4.6
      - comm==0.2.1
      - cssselect==1.2.0
      - debugpy==1.8.1
      - defusedxml==0.7.1
      - exceptiongroup==1.2.0
      - execnet==2.0.2
      - executing==2.0.1
      - fasteners==0.19
      - fastjsonschema==2.19.1
      - filelock==3.13.1
      - fqdn==1.5.1
      - h11==0.14.0
      - httpcore==1.0.4
      - httpx==0.27.0
      - idna==3.6
      - iniconfig==2.0.0
      - ipykernel==6.29.3
      - ipython==8.22.1
      - ipywidgets==8.1.2
      - isoduration==20.11.0
      - jedi==0.19.1
      - jinja2==3.1.3
      - json5==0.9.17
      - jsonpointer==2.4
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - jupyter==1.0.0
      - jupyter-console==6.6.3
      - jupyter-core==5.7.1
      - jupyter-events==0.9.0
      - jupyter-lsp==2.2.3
      - jupyter-server==2.12.5
      - jupyter-server-terminals==0.5.2
      - jupyterlab==4.1.2
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.25.3
      - jupyterlab-widgets==3.0.10
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - mdurl==0.1.2
      - mistune==3.0.2
      - nbclient==0.9.0
      - nbconvert==7.16.1
      - nbformat==5.9.2
      - notebook==7.1.1
      - notebook-shim==0.2.4
      - numpy==1.26.4
      - outcome==1.3.0.post0
      - overrides==7.7.0
      - packaging==23.2
      - pandas==2.2.1
      - pandocfilters==1.5.1
      - parameterized==0.9.0
      - parse==1.20.1
      - parse-type==0.6.2
      - pdbp==1.5.0
      - pexpect==4.9.0
      - pip==24.0
      - platformdirs==4.2.0
      - pluggy==1.4.0
      - prometheus-client==0.20.0
      - psutil==5.9.8
      - py==1.11.0
      - pycparser==2.21
      - pygments==2.17.2
      - pynose==1.5.0
      - pyotp==2.9.0
      - pysocks==1.7.1
      - pytest==8.0.2
      - pytest-html==2.0.1
      - pytest-metadata==3.1.1
      - pytest-ordering==0.6
      - pytest-rerunfailures==13.0
      - pytest-xdist==3.5.0
      - python-json-logger==2.0.7
      - pytz==2024.1
      - pyyaml==6.0.1
      - qtconsole==5.5.1
      - qtpy==2.4.1
      - referencing==0.33.0
      - requests==2.31.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.7.0
      - rpds-py==0.18.0
      - sbvirtualdisplay==1.3.0
      - selenium==4.18.1
      - seleniumbase==4.24.1
      - send2trash==1.8.2
      - setuptools==69.1.1
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soupsieve==2.5
      - stack-data==0.6.3
      - tabcompleter==1.3.0
      - terminado==0.18.0
      - tinycss2==1.2.1
      - tornado==6.4
      - traitlets==5.14.1
      - trio==0.24.0
      - trio-websocket==0.11.1
      - types-python-dateutil==2.8.19.20240106
      - typing-extensions==4.10.0
      - tzdata==2024.1
      - uri-template==1.3.0
      - urllib3==2.2.1
      - wcwidth==0.2.13
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.7.0
      - wheel==0.42.0
      - widgetsnbextension==4.0.10
      - wsproto==1.2.0
